// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

// Defines values for ErrorErrorCode.
const (
	ErrorErrorCodeConflict             ErrorErrorCode = "conflict"
	ErrorErrorCodeInternalError        ErrorErrorCode = "internal_error"
	ErrorErrorCodeNotFound             ErrorErrorCode = "not_found"
	ErrorErrorCodeUnsupportedMediaType ErrorErrorCode = "unsupported_media_type"
	ErrorErrorCodeValidationError      ErrorErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case ErrorErrorCodeConflict:
		return true
	case ErrorErrorCodeInternalError:
		return true
	case ErrorErrorCodeNotFound:
		return true
	case ErrorErrorCodeUnsupportedMediaType:
		return true
	case ErrorErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// CredentialField Metadata describing one credential field a provider requires.
type CredentialField struct {
	// Label Human-readable label for display in a credential form.
	Label string `json:"label"`

	// Name Machine-readable field key (e.g. `api_key`).
	Name string `json:"name"`

	// Secret Whether the field value must be masked/encrypted at rest.
	Secret bool `json:"secret"`
}

// CredentialPresence Whether a declared credential field currently has a stored value.
type CredentialPresence struct {
	// Configured Whether a value is currently stored for this field.
	Configured bool `json:"configured"`

	// Name Machine-readable field key (e.g. `api_key`).
	Name string `json:"name"`
}

// CredentialPresenceList defines model for CredentialPresenceList.
type CredentialPresenceList struct {
	Fields []CredentialPresence `json:"fields"`
}

// CredentialValues Full set of credential values for a provider, keyed by declared field name. Write-only: this payload is never echoed back by any read path.
type CredentialValues struct {
	// Values Field name → secret value. Must match the provider's declared credential fields exactly — unknown or missing keys are rejected.
	Values map[string]string `json:"values"`
}

// Error Canonical error envelope returned by every `/api/v1` error response.
type Error struct {
	Error struct {
		// Code Stable machine-readable error code.
		Code ErrorErrorCode `json:"code"`

		// Details Optional structured detail (e.g. field-level validation errors).
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Human-readable error message. Never contains internal detail on 5xx.
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode Stable machine-readable error code.
type ErrorErrorCode string

// Provider defines model for Provider.
type Provider struct {
	// CredentialFields Credential fields required to configure this provider.
	CredentialFields []CredentialField `json:"credentialFields"`

	// Enabled Whether the provider is currently enabled.
	Enabled bool `json:"enabled"`

	// Id Stable provider identifier.
	Id string `json:"id"`

	// Name Human-readable provider name.
	Name string `json:"name"`
}

// ProviderId defines model for ProviderId.
type ProviderId = string

// InternalError Canonical error envelope returned by every `/api/v1` error response.
type InternalError = Error

// NotFound Canonical error envelope returned by every `/api/v1` error response.
type NotFound = Error

// UnsupportedMediaType Canonical error envelope returned by every `/api/v1` error response.
type UnsupportedMediaType = Error

// ValidationError Canonical error envelope returned by every `/api/v1` error response.
type ValidationError = Error

// SetProviderCredentialsJSONRequestBody defines body for SetProviderCredentials for application/json ContentType.
type SetProviderCredentialsJSONRequestBody = CredentialValues
