// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for ErrorErrorCode.
const (
	ErrorErrorCodeConflict             ErrorErrorCode = "conflict"
	ErrorErrorCodeInternalError        ErrorErrorCode = "internal_error"
	ErrorErrorCodeNotFound             ErrorErrorCode = "not_found"
	ErrorErrorCodeUnsupportedMediaType ErrorErrorCode = "unsupported_media_type"
	ErrorErrorCodeValidationError      ErrorErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case ErrorErrorCodeConflict:
		return true
	case ErrorErrorCodeInternalError:
		return true
	case ErrorErrorCodeNotFound:
		return true
	case ErrorErrorCodeUnsupportedMediaType:
		return true
	case ErrorErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// CredentialField Metadata describing one credential field a provider requires.
type CredentialField struct {
	// Label Human-readable label for display in a credential form.
	Label string `json:"label"`

	// Name Machine-readable field key (e.g. `api_key`).
	Name string `json:"name"`

	// Secret Whether the field value must be masked/encrypted at rest.
	Secret bool `json:"secret"`
}

// CredentialPresence Whether a declared credential field currently has a stored value.
type CredentialPresence struct {
	// Configured Whether a value is currently stored for this field.
	Configured bool `json:"configured"`

	// Name Machine-readable field key (e.g. `api_key`).
	Name string `json:"name"`
}

// CredentialPresenceList defines model for CredentialPresenceList.
type CredentialPresenceList struct {
	Fields []CredentialPresence `json:"fields"`
}

// CredentialValues Full set of credential values for a provider, keyed by declared field name. Write-only: this payload is never echoed back by any read path.
type CredentialValues struct {
	// Values Field name → secret value. Must match the provider's declared credential fields exactly — unknown or missing keys are rejected.
	Values map[string]string `json:"values"`
}

// Error Canonical error envelope returned by every `/api/v1` error response.
type Error struct {
	Error struct {
		// Code Stable machine-readable error code.
		Code ErrorErrorCode `json:"code"`

		// Details Optional structured detail (e.g. field-level validation errors).
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Human-readable error message. Never contains internal detail on 5xx.
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode Stable machine-readable error code.
type ErrorErrorCode string

// Provider defines model for Provider.
type Provider struct {
	// CredentialFields Credential fields required to configure this provider.
	CredentialFields []CredentialField `json:"credentialFields"`

	// Enabled Whether the provider is currently enabled.
	Enabled bool `json:"enabled"`

	// Id Stable provider identifier.
	Id string `json:"id"`

	// Name Human-readable provider name.
	Name string `json:"name"`
}

// UsageMetric One usage data point captured in a provider's usage snapshot.
type UsageMetric struct {
	// Limit The provider's disclosed cap, or null if unlimited/unknown.
	Limit *int64 `json:"limit,omitempty"`

	// Name Metric name (e.g. `requests`, `spend`).
	Name string `json:"name"`

	// Remaining Provider-supplied remaining amount, or null if unknown.
	Remaining *int64 `json:"remaining,omitempty"`

	// ResetAt When this metric's window resets, or null if not disclosed.
	ResetAt *time.Time `json:"resetAt,omitempty"`

	// Unit Smallest integer unit the metric is expressed in (e.g. `usd_cents`, `tokens`) — no fractional/float quantities.
	Unit string `json:"unit"`
	Used int64  `json:"used"`

	// Window The window the metric covers (e.g. `day`, `month`).
	Window string `json:"window"`
}

// UsageSnapshot The latest-only usage snapshot for a provider. No history/time-series is retained — each collection replaces the previous snapshot.
type UsageSnapshot struct {
	// CollectedAt When this snapshot was collected, or null if the provider has never been collected (pending state).
	CollectedAt *time.Time `json:"collectedAt"`

	// LastError Error message from the most recent failed collection attempt, if any; absent/null otherwise.
	LastError *string       `json:"lastError,omitempty"`
	Metrics   []UsageMetric `json:"metrics"`
}

// ProviderId defines model for ProviderId.
type ProviderId = string

// InternalError Canonical error envelope returned by every `/api/v1` error response.
type InternalError = Error

// NotFound Canonical error envelope returned by every `/api/v1` error response.
type NotFound = Error

// UnsupportedMediaType Canonical error envelope returned by every `/api/v1` error response.
type UnsupportedMediaType = Error

// ValidationError Canonical error envelope returned by every `/api/v1` error response.
type ValidationError = Error

// SetProviderCredentialsJSONRequestBody defines body for SetProviderCredentials for application/json ContentType.
type SetProviderCredentialsJSONRequestBody = CredentialValues
